syslink: devh: Fix build break with SYSLINK_RECOVERY disabled
If we disable SYSLINK_RECOVERY option in drivers->syslink
->SYSLINK_RECOVERY, build breaks with below errors

drivers/built-in.o: In function `devh_notification_handler':
drivers/dsp/syslink/devh/44xx/devh44xx.c:103: undefined reference to
`ipc_recover_schedule'
drivers/built-in.o: In function `devh44xx_wdt_ipc_notifier_call':
drivers/dsp/syslink/devh/44xx/devh44xx.c:244: undefined reference to
`ipc_recover_schedule'
make: *** [.tmp_vmlinux1] Error 1

Fixed by moving ipc_revover_schedule function under SYSLINK_RECOVERY Flag.

Change-Id: Idb4de38bbe1e2586eebac9f76150616ea93d56f3
Signed-off-by: Shivananda Hebbar <x0hebbar@ti.com>